### ISSUE TITLE
mysterious favicon.ico

### ISSUE THREAD

**Issue by ktoddbrown** [ktoddbrown/ktoddbrown.github.io#7]
I'm getting an error when rendering this locally in jekyll saying that 'favicon.ico' not found after I click around the local hosted site. Not sure what this is referring to because grep doesn't show a reference to this file anywhere in the site files.

**Comment by SquidAndCrow** [comment]
It's a chrome thing (the code doesn't call for it, the browser does), I'll toss in the marble as a favicon; should take care of it.

**Comment by ktoddbrown** [comment]
You figured it out! YEA!
